In [64]:
from PIL import Image
from numpy import asarray
import numpy as np

In [87]:
img = Image.open('ftc-grey.bmp').convert('L')

In [88]:
numpydata = asarray(img)

In [89]:
numpydata.shape

(300, 300)

In [90]:
numpydata

array([[ 41,  41,  42, ..., 108, 109, 109],
       [ 42,  42,  43, ..., 109, 109, 110],
       [ 42,  42,  42, ..., 110, 110, 110],
       ...,
       [109, 109, 110, ..., 253, 253, 253],
       [109, 109, 110, ..., 253, 253, 254],
       [109, 109, 110, ..., 254, 253, 254]], dtype=uint8)

In [91]:
tnd = numpydata

In [92]:
text = '72 101 108 108 111 32 119 111 114 108 100 32 102 114 111 109 32 70 117 116 117 114 101 32 116 101 99 104 110 111 108 111 103 121 32 99 108 117 98'
arr_text = text.split(" ")

In [93]:
arr_text = list(map(int, arr_text))

In [94]:
tnd[250][149:188] = np.array(arr_text)

In [95]:
tnd[250][149:188]

array([ 72, 101, 108, 108, 111,  32, 119, 111, 114, 108, 100,  32, 102,
       114, 111, 109,  32,  70, 117, 116, 117, 114, 101,  32, 116, 101,
        99, 104, 110, 111, 108, 111, 103, 121,  32,  99, 108, 117,  98],
      dtype=uint8)

In [96]:
from matplotlib import cm
im = Image.fromarray(np.uint8(tnd))

In [97]:
im.save('puzzle.bmp')

In [98]:
img = Image.open('puzzle.bmp')

In [99]:
numpydata = asarray(img)

In [100]:
numpydata[250][149:188]

array([ 72, 101, 108, 108, 111,  32, 119, 111, 114, 108, 100,  32, 102,
       114, 111, 109,  32,  70, 117, 116, 117, 114, 101,  32, 116, 101,
        99, 104, 110, 111, 108, 111, 103, 121,  32,  99, 108, 117,  98],
      dtype=uint8)